### ISSUE TITLE
No Images Loading

### ISSUE THREAD

**Issue by DraxIndustries79** [scientist-softserv/arce#60]
No images or thumbnails are loading for works in archives.arce.org.

**Comment by labradford** [comment]
UCLA feed is down.

**Comment by DraxIndustries79** [comment]
From Dawn Childress:  "We haven’t made any changes yet, and won’t until we agree on a timeline. I did notice that ARCE Archives and IDEP both are not loading images (records too in IDEP), so I thought Solr might need a reboot. We put in a ticket to DGI on Friday after I noticed it. I thought they would have fixed it by now, but perhaps it’s more than a Solr restart issue? I’ll check in with Geno to see if there are any updates and get back to you."

**Comment by labradford** [comment]
1/11 everything is back up. Images are loading in the viewer and thumbnails are appearing correctly
