### ISSUE TITLE
Update Scrolling Banner

### ISSUE THREAD

**Issue by DraxIndustries79** [scientist-softserv/arce#61]
Update scrolling Collections Preview banner.  

**Acceptance:**
- [ ] Banner scroll whould read:  **Conservation and Documentation of the Wall Paintings at Red Monastery, Conservation and Documentation of St. Anthony Wall Paintings, Historic Cairo Architectural Mapping, Coptic Icons Documentation**

**Comment by aprilrieger** [comment]
on staging
<img width="1475" alt="Screenshot 2023-02-01 at 19 58 05" src="https://user-images.githubusercontent.com/63515648/216228491-03b516ce-afe9-42c9-9509-aa71fbcac7ef.png">

**Comment by aprilrieger** [comment]
Deployed to Production
<img width="1254" alt="Screenshot 2023-02-03 at 16 59 39" src="https://user-images.githubusercontent.com/63515648/216736779-6a7b82f4-7ac1-4467-89ae-0b5ccce82b92.png">
