### ISSUE TITLE
[Spike] ARCE instability

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/arce#67]
# Summary

ARCE has been flapping for the last week and its has been progressively getting worse.  There are logs in slack, as well as outage times and a sentry error.  But Rob did mention that this could be related to instability on r2-pals and the solution may be to move it to Besties.  

# Acceptance Criteria

- [x] Research what is wrong and plan what we should do to resolve it. 
- [ ] Create ticket/s for plan unless it gets resolved during the time.

**Comment by aprilrieger** [comment]
Arce currently has the following resources:

- web
- worker
- solr
- postgresql db

My suggestion:
Deploy the workload to a more stable cluster (r2-besties)

Things that need to happen:

- backup/restore sql db dump
- backup/restore solr
- work to update the deployment files and env variables to accommodate the switch to the new cluster
- transfer the dns to the loadbalancer (more risky as I dont really understand this part as I didnt set it up)

**Comment by crisr15** [comment]
My only objection to this is that we may want to keep staging and production separate, so moving another staging instance onto besties may not be our best approach.  Could we do the production instance, but change the domain to be a notch8.cloud address until we were finished testing, and then we could update the DNS to move it from one stack to the other without the down time?

**Comment by crisr15** [comment]
Additionally, it feels like r2-staging is overcrowded and under resourced.  Is Besties on newer devices/technology and we want a staging instance that matches it?

**Comment by aprilrieger** [comment]
Yes I agree with you about not having a staging instance on besties. I can and agree with your approach of deploying like we were going to deploy a prod instance on besties but point to our  notch8.cloud address. I meant "staging" as in a place to test that things are correct before making the swap.

**Comment by orangewolf** [comment]
these look great. I've updated the proposed instructions with out the staging / productoin 2 step and I dont think it is worth migrating the solr copy. Confirm with LeaAnn, but I think this site indexes in a couple of mintues so its better just to run the reindex and save the headache of the solr migration.

**Comment by aprilrieger** [comment]
> these look great. I've updated the proposed instructions with out the staging / productoin 2 step and I dont think it is worth migrating the solr copy. Confirm with LeaAnn, but I think this site indexes in a couple of mintues so its better just to run the reindex and save the headache of the solr migration.

Confirming that I spoke with Lea Ann, she stated that it it takes approx 10-20 minutes to reindex it all. So much easier to reindex than migrate solr.

**Comment by crisr15** [comment]
Ticket for work #70.
