### ISSUE TITLE
ARCE OAI Won't Update

### ISSUE THREAD

**Issue by DraxIndustries79** [scientist-softserv/arce#87]
## Story
We have updated the old OAI link from https://dl.library.ucla.edu/oai2/ to the new one https://digital.library.ucla.edu/catalog/oai and loaded the items from the admin panel. However, the items have not been updated.

Could you please refer this issue to Kevin to help us identify if there is a missing step we need to complete?

Kevin's Note:  I'm aware we don't have enough info to figure out what's going on, so maybe we first ask what we need access to.  

**If this is more than a 30-minute task, let Kevin know...we're not getting paid by them**

# Acceptance
- [x] What questions do we need to ask to help here?
- [x] Let Urska know what the issue is

**Comment by aprilrieger** [comment]
There was work to upgrade ucla's oai feed that involved more than just updating the url for the feed, there were code changes that needed to get made as well.

https://github.com/UCLALibrary/oral-history/pull/75/files
